### ISSUE TITLE
Individual infusion time

### ISSUE THREAD

**Issue by ksl31** [cacha0227/ncappc#12]
Hi Chayan,

Is it possible to have a column with different infusion time for different subjects for IV infusion route instead of the current single infusion time for all subjects? 

Thank you!

**Comment by cacha0227** [comment]
Dear ksl31,

Thanks a lot for your valuable suggestions. Most of them will be very useful modification/addition to the package.

I am currently swamped with other work. So it might take some time to update the package to include your suggestion. I will update the GitHub first and once I am done with all updates, I will update the CRAN version.

I sincerely appreciate your input in helping me to improve the package. I will be very happy if you could introduce yourself.

Best,
Chayan.

**Comment by ksl31** [comment]
Hi Chayan,
Thank you for your  email and your work in improving the package. It really does make a difference for people like me who are looking to find alternatives to Winnolin. My name is Siew Lee and I work for a pharma in the field of PK/PD.
I look forward to your updated package.
Thank you.
Best Regards,Siew Lee

Date: Fri, 24 Jun 2016 01:52:39 -0700
