### ISSUE TITLE
Number of decimal place in parameters

### ISSUE THREAD

**Issue by ksl31** [cacha0227/ncappc#7]
Is it possible to increase the number of decimal places from the current of four? Parameters with very small value will be inaccurate if only 4 decimal place is display, e.g. 0.0020288625 in Winnonlin is only displayed as 0.002 in ncappc. Thanks!

**Comment by cacha0227** [comment]
Dear User,

Thank you for your suggestions. I will implement the necessary changes in the package and let you know when the updated packaged is available.

Best,
Chayan.
