### ISSUE TITLE
Steady-state calculations problem

### ISSUE THREAD

**Issue by ksl31** [cacha0227/ncappc#8]
Hi Chayan,
I'm having trouble getting the parameters for steady state data. My dataset has conc=Cmin when t=0. Could you please help?  Below is my settings.

ncappc(obsFile = jjdata,
       str1Nm = 'Subject',  
       str2Nm = 'Day',  
       concUnit = 'ng/mL', 
       timeUnit = 'h',
       doseUnit = 'ng',
       idNmObs = 'Subject',
       timeNmObs = 'time',
       concNmObs = 'conc',
       AUCTimeRange =NULL,
       backExtrp = FALSE,
       doseAmtNm = 'Dose',
       adminType = 'extravascular',
       doseType = 'ss',
       Tau=24,
       method = 'linear-log',
       doseTime = 0,
       evid = FALSE
)

**Error in matrix(unlist(value, recursive = FALSE, use.names = FALSE), nrow = nr,  : 
  length of 'dimnames' [2] not equal to array extent**

**Comment by cacha0227** [comment]
Hi Siew,

It is impossible for me to identify the problem that you are having with the steady state data without looking at the data set. Would it be possible for you to share a part the data set with me?

Best,
Chayan.

**Comment by ksl31** [comment]
**Hi Chayan,
I used one of the sample datasets in the "datasets" package. Below is my code.** 

Theo=datasets::Theoph 

jjdata=Theo[Theo$Subject=="1",]

library(ncappc)

ncappc(obsFile = jjdata,  
       concUnit = 'ng/mL', 
       timeUnit = 'h',
       doseUnit = 'ng',
       idNmObs = 'Subject',
       timeNmObs = 'Time',
       concNmObs = 'conc',
       AUCTimeRange =NULL,
       backExtrp = FALSE,
       doseAmtNm = 'Dose',
       adminType = 'extravascular',
       doseType = 'ss',
       Tau=24,
       TI = NULL,
       method = 'linear-log',
       doseTime = 0,
       evid = FALSE
)

**I got the following error message.** 

Error in if (nconc[r + 1] >= nconc[r] | nconc[r + 1] <= 0 | nconc[r] <=  : 
  missing value where TRUE/FALSE needed
In addition: Warning messages:
1: In min(ntime) : no non-missing arguments to min; returning Inf
2: In min(ntime) : no non-missing arguments to min; returning Inf
3: In max(nconc) : no non-missing arguments to max; returning -Inf
4: In max(which(nconc == tail(nconc[nconc > 0], 1))) :
  no non-missing arguments to max; returning -Inf

**Please help. Thanks a lot!**

**Comment by cacha0227** [comment]
Hi Siew,

I will look into this issue as soon as I can. But I am afraid it will not happen until next week.

Best,
Chayan.
